# Generated by Django 4.2.6 on 2023-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_week',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Неделя проекта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Уровень ученика'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
