# Generated by Django 4.2.6 on 2023-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0002_call_time_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm',
            name='call_time',
        ),
        migrations.AddField(
            model_name='pm',
            name='call_time',
            field=models.ManyToManyField(to='pr_auto.call_time'),
        ),
    ]
