# Generated by Django 4.2.6 on 2023-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0002_student_project_week_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='call_time',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Удобное время для созвона'),
        ),
    ]
