# Generated by Django 4.2.6 on 2023-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0003_student_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_status',
            field=models.BooleanField(default=False, verbose_name='Статус регистрации в проекте'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'email', 'telegram_id'), name='user_author'),
        ),
    ]
