# Generated by Django 4.2.6 on 2023-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email ученика'),
        ),
    ]
