# Generated by Django 4.2.6 on 2023-10-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0004_level_alter_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название проекта')),
                ('brief', models.FileField(max_length=254, upload_to=None)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_auto.level', verbose_name='Уровень проекта')),
            ],
        ),
    ]
