# Generated by Django 4.2.6 on 2023-10-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0005_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_time',
            name='call_time',
            field=models.TimeField(verbose_name='Время созвона!'),
        ),
    ]
