# Generated by Django 4.2.6 on 2023-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0005_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_week', models.CharField(max_length=50, verbose_name='Неделя проекта')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='project',
        ),
        migrations.AddField(
            model_name='group',
            name='call_time',
            field=models.CharField(blank=True, max_length=25, verbose_name='Время созвона группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='project_week',
            field=models.CharField(blank=True, max_length=25, verbose_name='Неделя проекта'),
        ),
    ]
