# Generated by Django 4.2.6 on 2023-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0006_alter_call_time_call_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_time',
            name='call_time',
            field=models.CharField(max_length=50, verbose_name='Время созвона'),
        ),
    ]
