# Generated by Django 4.2.6 on 2023-10-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_auto', '0006_project_week_remove_group_project_group_call_time_and_more'),
        ('pr_auto', '0007_alter_call_time_call_time'),
    ]

    operations = [
    ]
